@REM 
@REM Copyright 2022 Google LLC
@REM 
@REM Licensed under the Apache License, Version 2.0 (the "License");
@REM you may not use this file except in compliance with the License.
@REM You may obtain a copy of the License at
@REM 
@REM      http://www.apache.org/licenses/LICENSE-2.0
@REM 
@REM Unless required by applicable law or agreed to in writing, software
@REM distributed under the License is distributed on an "AS IS" BASIS,
@REM WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
@REM See the License for the specific language governing permissions and
@REM limitations under the License.
@REM 

@echo off
@REM Detects whether both /common and /bazel-out are regular directories and deletes /bazel-out if so.

set ROOT=%~dp0

@REM If common is a junction, we're probably in %USERPROFILE%\_bazel%USERNAME%\execroot\cdc_file_transfer.
@REM Things will work fine.
fsutil reparsepoint query %ROOT%\common > nul && exit /b 0

@REM If bazel-out is already a junction, we're probably in the regular root dir. Things will work fine.
if not exist %ROOT%\bazel-out (
   exit /b 0
)
fsutil reparsepoint query %ROOT%\bazel-out > nul && exit /b 0

@REM bazel-out is not a junction, but it should be, so delete it
echo Deleting %ROOT%\bazel-out (probably autogenerated by VS, but Bazel wants it to be a junction)
rmdir /S /Q %ROOT%\bazel-out
